# Define port for the GraphQL API
port: 8888

database:
  bolt:
    hosts:
      - 127.0.0.1:6362
    username: ""
    password: ""
    pool_size: 10
  memcached:
    hosts:
      - 127.0.0.1:11211
    pool_size: 10
