name: Gravitalia/bazel

permissions:
  contents: read

on: push

jobs:
  bazel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: ubuntu-latest
          name: Linux Ubuntu
    name: Build (${{ matrix.name || matrix.target }})
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-bazel
    - name: Install Node dependencies
      run: pnpm install --no-frozen-lockfile
    - name: Run builds
      run: bazel build //graphql:graphql
      shell: bash
    - name: Run tests
      run: bazel test //graphql:graphql
      shell: bash
